-- =============================================================
-- data-derby.sql - Auto-generated DB snapshot
-- Generated: 2026-06-08 00:28:41
-- Executed automatically on app startup.
-- Inserts are idempotent (WHERE NOT EXISTS guards).
-- =============================================================

SELECT 1 FROM SYSIBM.SYSDUMMY1;

INSERT INTO USERS (ID, ACTIVE_SESSION_EXPIRES_AT, ACTIVE_SESSION_TOKEN_HASH, EMAIL, NAME, PASSWORD_HASH, PHONE_NUMBER, ROLE, USERNAME)
SELECT 1, '2026-06-07 17:49:09.878146', '5d79bb8bb03fb665a8bae9d116f42b64d926179e6c29ec93cde6bb326ba6d0e2', 'nirvikghoshbdmi@gmail.com', 'Admin', '$2a$10$XGTtj4s5LtNpW1o12TWHJuuj.WJuNLY1/CVAPSJ6qW20eUt.USN1C', '8584982009', 'ADMIN', 'admin1' FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE USERNAME = 'admin1');
INSERT INTO USERS (ID, ACTIVE_SESSION_EXPIRES_AT, ACTIVE_SESSION_TOKEN_HASH, EMAIL, NAME, PASSWORD_HASH, PHONE_NUMBER, ROLE, USERNAME)
SELECT 101, CAST(NULL AS TIMESTAMP), CAST(NULL AS VARCHAR(255)), 'admin@usedcars.local', 'System Admin', '$2a$10$a1AtrKn3Lag0Y3QqgYO6sOYm5JTZgyEAePNNt71Cc30u3lyUnKq4.', '0000000000', 'ADMIN', 'admin' FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE USERNAME = 'admin');
INSERT INTO USERS (ID, ACTIVE_SESSION_EXPIRES_AT, ACTIVE_SESSION_TOKEN_HASH, EMAIL, NAME, PASSWORD_HASH, PHONE_NUMBER, ROLE, USERNAME)
SELECT 102, CAST(NULL AS TIMESTAMP), CAST(NULL AS VARCHAR(255)), 'seller1@usedcars.local', 'Vikram Seller', '$2a$10$17wmXdjCqtA9sDAn4B.FlOIuryUlAlS3DfWbnBL0LfdV69CaXX5aW', '9876543210', 'USER', 'seller1' FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE USERNAME = 'seller1');
INSERT INTO USERS (ID, ACTIVE_SESSION_EXPIRES_AT, ACTIVE_SESSION_TOKEN_HASH, EMAIL, NAME, PASSWORD_HASH, PHONE_NUMBER, ROLE, USERNAME)
SELECT 103, CAST(NULL AS TIMESTAMP), CAST(NULL AS VARCHAR(255)), 'buyer1@usedcars.local', 'Ravi Buyer', '$2a$10$17wmXdjCqtA9sDAn4B.FlOIuryUlAlS3DfWbnBL0LfdV69CaXX5aW', '9123456780', 'USER', 'buyer1' FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (SELECT 1 FROM USERS WHERE USERNAME = 'buyer1');
-- USERS : 4 row(s)

-- CARS : (empty)

-- PAYMENTS : (empty)

-- PURCHASE_ORDERS : (empty)

-- RECENT_VIEWS : (empty)

-- WISHLIST_ITEMS : (empty)

-- FEEDBACK : (empty)

-- SUPPORT_TICKETS : (empty)

-- TICKET_RESPONSES : (empty)

